import os
from pathlib import Path

from dotenv import load_dotenv


PROJECT_ROOT = Path(__file__).resolve().parent
ENV_PATH = PROJECT_ROOT / ".env"

load_dotenv(ENV_PATH)

HF_ACCESS_TOKEN = os.getenv("HF_ACCESS_TOKEN")

DATASET_NAME = "RadGenome/RadGenome-ChestCT"
DATASET_CONFIG = "grounded reports"
EXPECTED_FIELDS = ["Volumename", "Anatomy", "Sentence"]

RAW_DATASET_FILE = None
PREPROCESSING_DIR = PROJECT_ROOT / "data" / "preprocessing"
PREPROCESSING_SLICES_DIR = PREPROCESSING_DIR / "slices"
PREPROCESSING_EXCLUDED_STUDIES_PATH = PREPROCESSING_DIR / "excluded_studies.json"

VOLUME_EXTENSION = ""
DATASET_SIZE = 100
DOWNLOAD_BATCH_SIZE = 10
LOG_EVERY_N_ROWS = 10000
ALLOWED_ANATOMIES = ["lung"]

MAX_TEXT_LENGTH_CHARS = 1200
MIN_SENTENCE_LENGTH_CHARS = 3
JOIN_SENTENCES_WITH = " "
DROP_DUPLICATE_SENTENCES = True
REQUIRE_NON_EMPTY_TEXT = True

SLICE_POSITIONS = [0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85]
SLICE_IMAGE_SIZE = 224
LUNG_HU_MIN = -950
LUNG_HU_MAX = -300
LUNG_MIN_FRACTION = 0.08
LUNG_MIN_RANGE_SLICES = 8
LUNG_RANGE_PADDING_SLICES = 1
LUNG_FOREGROUND_HU_THRESHOLD = -900
LUNG_PEAK_RELATIVE_THRESHOLD = 0.6
LUNG_FRACTION_SMOOTHING_WINDOW = 3
LUNG_PEAK_MASS_COVERAGE = 0.85
HU_SANITIZE_MIN = -1024
HU_SANITIZE_MAX = 3071
SLICE_PAD_HU_VALUE = -1000
MULTI_WINDOW_RANGES = (
    (-1000, 200),
    (-950, -350),
    (-160, 240),
)
USE_CANONICAL_ORIENTATION = True
TARGET_VOXEL_SPACING = (1.5, 1.5, 3.0)
MIN_VALID_VOXEL_SPACING = 0.01

SEED = 42
TRAIN_RATIO = 0.8
VAL_RATIO = 0.1
TEST_RATIO = 0.1


def to_printable():
    return {
        "PROJECT_ROOT": str(PROJECT_ROOT),
        "HF_ACCESS_TOKEN": "***" if HF_ACCESS_TOKEN else None,
        "DATASET_NAME": DATASET_NAME,
        "DATASET_CONFIG": DATASET_CONFIG,
        "SOURCE_SPLITS": ["train", "validation"],
        "EXPECTED_FIELDS": EXPECTED_FIELDS,
        "RAW_DATASET_FILE": str(RAW_DATASET_FILE) if RAW_DATASET_FILE else None,
        "PREPROCESSING_DIR": str(PREPROCESSING_DIR),
        "PREPROCESSING_SLICES_DIR": str(PREPROCESSING_SLICES_DIR),
        "VOLUME_EXTENSION": VOLUME_EXTENSION,
        "DATASET_SIZE": DATASET_SIZE,
        "DOWNLOAD_BATCH_SIZE": DOWNLOAD_BATCH_SIZE,
        "LOG_EVERY_N_ROWS": LOG_EVERY_N_ROWS,
        "ALLOWED_ANATOMIES": ALLOWED_ANATOMIES,
        "MAX_TEXT_LENGTH_CHARS": MAX_TEXT_LENGTH_CHARS,
        "MIN_SENTENCE_LENGTH_CHARS": MIN_SENTENCE_LENGTH_CHARS,
        "JOIN_SENTENCES_WITH": JOIN_SENTENCES_WITH,
        "DROP_DUPLICATE_SENTENCES": DROP_DUPLICATE_SENTENCES,
        "REQUIRE_NON_EMPTY_TEXT": REQUIRE_NON_EMPTY_TEXT,
        "SLICE_POSITIONS": SLICE_POSITIONS,
        "SLICE_IMAGE_SIZE": SLICE_IMAGE_SIZE,
        "LUNG_HU_MIN": LUNG_HU_MIN,
        "LUNG_HU_MAX": LUNG_HU_MAX,
        "LUNG_MIN_FRACTION": LUNG_MIN_FRACTION,
        "LUNG_MIN_RANGE_SLICES": LUNG_MIN_RANGE_SLICES,
        "LUNG_RANGE_PADDING_SLICES": LUNG_RANGE_PADDING_SLICES,
        "LUNG_FOREGROUND_HU_THRESHOLD": LUNG_FOREGROUND_HU_THRESHOLD,
        "LUNG_PEAK_RELATIVE_THRESHOLD": LUNG_PEAK_RELATIVE_THRESHOLD,
        "LUNG_FRACTION_SMOOTHING_WINDOW": LUNG_FRACTION_SMOOTHING_WINDOW,
        "LUNG_PEAK_MASS_COVERAGE": LUNG_PEAK_MASS_COVERAGE,
        "HU_SANITIZE_MIN": HU_SANITIZE_MIN,
        "HU_SANITIZE_MAX": HU_SANITIZE_MAX,
        "SLICE_PAD_HU_VALUE": SLICE_PAD_HU_VALUE,
        "MULTI_WINDOW_RANGES": [list(window) for window in MULTI_WINDOW_RANGES],
        "USE_CANONICAL_ORIENTATION": USE_CANONICAL_ORIENTATION,
        "TARGET_VOXEL_SPACING": TARGET_VOXEL_SPACING,
        "MIN_VALID_VOXEL_SPACING": MIN_VALID_VOXEL_SPACING,
        "SEED": SEED,
        "TRAIN_RATIO": TRAIN_RATIO,
        "VAL_RATIO": VAL_RATIO,
        "TEST_RATIO": TEST_RATIO,
    }
